name: build and push to ghcr
on:
    push:
        branches:
            - main
jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build and push image to ghcr
              run: |
                    docker login --username prs2304 --password ${{secrets.GH_PAT}} ghcr.io
                    docker build . --tag ghcr.io/prs2304/python:v3
                    docker push ghcr.io/prs2304/python:v3



